from __future__ import annotations
from typing import Protocol, Callable, Any

State = Any
Transfer = Callable[[Any], None]

class RobotEngine(Protocol):
    def move(self, transfer: Transfer, distance: int, state: State) -> State: ...
    def turn(self, transfer: Transfer, angle: int, state: State) -> State: ...
    def set_state(self, transfer: Transfer, mode: str, state: State) -> State: ...
    def start(self, transfer: Transfer, state: State) -> State: ...
    def stop(self, transfer: Transfer, state: State) -> State: ...
